spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sedi
    driverClassName: org.postgresql.Driver
    username: admin
    password: "sedi@uni1"
  jpa:
    properties:
      dialect: PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
