spring:
  datasource:
    url: jdbc:h2:mem:;INIT=RUNSCRIPT FROM '../db/setup_db.sql';
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    properties:
      dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
