version: '2'

services:
  dashboard:
    image: sedichile/dashboard
    depends_on:
      - db
    ports:
      - "3000:3000"
    container_name: sedi-grafana
    restart: always
    environment:
      - GF_USERS_DEFAULT_THEME=light
  db:
    image: sedichile/database
    ports:
      - "5432:5432"
    container_name: sedi-postgres
    restart: always
  platformapp:
    image: sedichile/platformapp
    depends_on:
      - db
    ports:
      - "8080:8080"
    container_name: sedi-platformapp
    restart: always

