{
 "title": "Water Level Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Measurement ",
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "well",
     "query": "SELECT \"water_level\" FROM \"well\" WHERE $timeFilter order by time desc LIMIT 1",
     "select": [
      [
       { "params": [ "water_level" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Level over Time",
   "type": "graph",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Water Level in Meter" }
   ],
   "targets": [
    {
     "measurement": "well",
     "query": "SELECT \"water_level\" FROM \"well\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "water_level" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Water Level",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "well",
     "select": [
      [
       { "params": [ "water_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water Level Values",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "well",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       { "params": [ "Well Id" ], "type": "alias" }
      ],
      [
       { "params": [ "water_level" ], "type": "field" },
       { "params": [ "Water Level (in m)" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}