{
 "title": "Well Inspection",
 "description": "A Detailed Overview of one Well",
 "tags": [
  "drilldown",
  "well",
  "detailed"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "w_id", "label": "Select target Well", "query": "SELECT\n    w_id\nFROM well" }
  ]
 },
 "panels": [
  {
   "title": "Well Location",
   "type": "grafana-worldmap-panel",
   "description": "Shows the Location of the selected Well",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  m_timestamp AS \"time\",\r\n  m_water_level,\r\n  m_phvalue,\r\n  m_temperature,\r\n  w_lat,\r\n  w_long,\r\n  w_name\r\nFROM measurement\r\nJOIN well w on m_wellid = w_id\r\nWHERE w_id = [[w_id]]\r\nORDER BY time desc LIMIT 1"
    }
   ]
  },
  {
   "title": "Current water level in percent",
   "type": "marcuscalidus-svg-panel",
   "description": "The fill of the well in percent",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 0 },
   "format": "short",
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_water_level,\n  m_phvalue,\n  m_temperature,\n  w_lat,\n  w_long,\n  w_name,\n  (m_water_level/(w_diameter * w_maxdepth)) as percentage\nFROM measurement\nJOIN well w on m_wellid = w_id\nWHERE w_id = [[w_id]] and $__timeFilter(m_timestamp)\nORDER BY time desc LIMIT 1"
    }
   ]
  },
  {
   "title": "Average Ph-Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_phvalue\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_temperature\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Water level over time",
   "type": "graph",
   "description": "Shows the development of the water level in the selected timeframe",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_water_level\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ph-Value over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Ph-Value" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_phvalue\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp)\nORDER BY 1"
    }
   ]
  }
 ]
}