{
 "title": "Well Inspection",
 "description": "A Detailed Overview of one Well",
 "tags": [
  "drilldown",
  "well",
  "detailed"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "w_id", "label": "Select target Well", "query": "SELECT\n    w_id\nFROM well" }
  ]
 },
 "panels": [
  {
   "title": "Well Location",
   "type": "grafana-worldmap-panel",
   "description": "Shows the Location of the selected Well",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\r\n  m_timestamp AS \"time\",\r\n  cast(m_value as double precision) / ( well.w_diameter * well.w_maxdepth ) as level_percentage,\r\n  w_lat,\r\n  w_long,\r\n  ('<span style=\"color:black\">Water Level of Well ' || w_name || '</span>')  as tooltip\r\nFROM measurement\r\nJOIN well on m_fk_wellid = w_id\r\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\r\nWHERE w_id = '[[w_id]]' and sensor_type.st_value = 'level'\r\nORDER BY time desc LIMIT 1"
    }
   ]
  },
  {
   "title": "Current water level in percent",
   "type": "marcuscalidus-svg-panel",
   "description": "The fill of the well in percent",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  w_lat,\n  w_long,\n  w_name,\n  (cast(m_value as double precision)/(w_maxdepth)) as percentage\nFROM measurement\nJOIN well w on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and $__timeFilter(m_timestamp) and sensor_type.st_value = 'level'\nORDER BY time desc LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Well name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT\n  w_name\nFROM\n  well\nWHERE\n  w_id = '[[w_id]]'\n"
    }
   ]
  },
  {
   "title": "Current Ph value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  w_name,\n  cast(m_value as double precision)\nFROM measurement\nJOIN well w on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and $__timeFilter(m_timestamp) and sensor_type.st_value = 'ph'\nORDER BY time desc LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  w_name,\n  cast(m_value as double precision)\nFROM measurement\nJOIN well w on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and $__timeFilter(m_timestamp) and sensor_type.st_value = 'temp'\nORDER BY time desc LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Water level over time",
   "type": "graph",
   "description": "Shows the development of the water level in the selected timeframe",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Water level in meter" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  cast(m_value as double precision) as water_level_value,\n  w_name\nFROM measurement\nJOIN well on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and sensor_type.st_value = 'level' and $__timeFilter(m_timestamp)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Ph-Value over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Ph-Value" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  cast(m_value as double precision) as ph_value,\n  w_name\nFROM measurement\nJOIN well on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and sensor_type.st_value = 'ph' and  $__timeFilter(m_timestamp)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Temperature in °C" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  cast(m_value as double precision) as tmp_value,\n  w_name\nFROM measurement\nJOIN well on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and sensor_type.st_value = 'temp' and $__timeFilter(m_timestamp)\nORDER BY time\n  \n"
    }
   ]
  },
  {
   "title": "Average Ph-Value",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  cast(m_value as decimal),\n  w_name\nFROM measurement\nJOIN well on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and sensor_type.st_value = 'ph' and $__timeFilter(m_timestamp)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  cast(m_value as decimal),\n  w_name\nFROM measurement\nJOIN well on m_fk_wellid = w_id\nJOIN sensor_type on measurement.sensor_type_st_id = sensor_type.st_id\nWHERE w_id = '[[w_id]]' and sensor_type.st_value = 'temp' and $__timeFilter(m_timestamp)\nORDER BY time"
    }
   ]
  }
 ]
}